<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="2" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Regression Testing" duration-ms="37368" started-at="2020-11-08T03:49:23Z" finished-at="2020-11-08T03:50:01Z">
    <groups>
    </groups>
    <test name="Regression Test" duration-ms="37368" started-at="2020-11-08T03:49:23Z" finished-at="2020-11-08T03:50:01Z">
      <class name="com.companyName.ProjectName.TestCases.TC02_VerfityAlreadyRegisterUser">
        <test-method status="SKIP" signature="isSkip()[pri:0, instance:com.companyName.ProjectName.TestCases.TC02_VerfityAlreadyRegisterUser@28eaa59a]" name="isSkip" is-config="true" duration-ms="1" started-at="2020-11-08T09:20:01Z" finished-at="2020-11-08T09:20:01Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping Test case as it's Run Mode is set to N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping Test case as it's Run Mode is set to N
	at com.companyName.ProjectName.TestCases.TC02_VerfityAlreadyRegisterUser.isSkip(TC02_VerfityAlreadyRegisterUser.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isSkip -->
        <test-method status="SKIP" signature="verfityAlreadyRegisterUser(java.util.Hashtable)[pri:0, instance:com.companyName.ProjectName.TestCases.TC02_VerfityAlreadyRegisterUser@28eaa59a]" name="verfityAlreadyRegisterUser" duration-ms="0" started-at="2020-11-08T09:20:01Z" data-provider="Data_Collections" finished-at="2020-11-08T09:20:01Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping Test case as it's Run Mode is set to N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping Test case as it's Run Mode is set to N
	at com.companyName.ProjectName.TestCases.TC02_VerfityAlreadyRegisterUser.isSkip(TC02_VerfityAlreadyRegisterUser.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfityAlreadyRegisterUser -->
      </class> <!-- com.companyName.ProjectName.TestCases.TC02_VerfityAlreadyRegisterUser -->
      <class name="com.companyName.ProjectName.TestCases.TC01_CreatAnAccountNewCustomer">
        <test-method status="PASS" signature="init()[pri:0, instance:com.companyName.ProjectName.TestCases.TC01_CreatAnAccountNewCustomer@7ed7259e]" name="init" is-config="true" duration-ms="232" started-at="2020-11-08T09:19:23Z" finished-at="2020-11-08T09:19:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="isSkip()[pri:0, instance:com.companyName.ProjectName.TestCases.TC01_CreatAnAccountNewCustomer@7ed7259e]" name="isSkip" is-config="true" duration-ms="4" started-at="2020-11-08T09:19:23Z" finished-at="2020-11-08T09:19:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isSkip -->
        <test-method status="FAIL" signature="creatAnAccountNewCustomer(java.util.Hashtable)[pri:0, instance:com.companyName.ProjectName.TestCases.TC01_CreatAnAccountNewCustomer@7ed7259e]" name="creatAnAccountNewCustomer" duration-ms="35267" started-at="2020-11-08T09:19:23Z" data-provider="Data_Collections" finished-at="2020-11-08T09:19:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Year=1990, Contact_No=23131324, Month=May, Name=Ruchita, Address=Pune, Email_ID=loginTest12346@test.com, Password=dadad@dad21, LastName=XYZ, Day=5, FirstName=Ruchita, Page_Title=My Store}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Issue while selecting value from dropdown:-Cannot locate option with value: May
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:42:16'
System info: host: 'LIN51007546', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: unknown]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Issue while selecting value from dropdown:-Cannot locate option with value: May
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:42:16'
System info: host: 'LIN51007546', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: unknown
	at org.testng.Assert.fail(Assert.java:93)
	at com.companyName.ProjectName.utilities.CommonMethods.selectByValue(CommonMethods.java:96)
	at com.companyName.ProjectName.pages.PersonalInfomation.enterPersonalInformation(PersonalInfomation.java:26)
	at com.companyName.ProjectName.TestCases.TC01_CreatAnAccountNewCustomer.creatAnAccountNewCustomer(TC01_CreatAnAccountNewCustomer.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creatAnAccountNewCustomer -->
      </class> <!-- com.companyName.ProjectName.TestCases.TC01_CreatAnAccountNewCustomer -->
      <class name="com.companyName.ProjectName.TestCases.TC03_CreateNewAndVerifyExistingUser">
        <test-method status="SKIP" signature="isSkip()[pri:0, instance:com.companyName.ProjectName.TestCases.TC03_CreateNewAndVerifyExistingUser@3427b02d]" name="isSkip" is-config="true" duration-ms="1" started-at="2020-11-08T09:20:01Z" finished-at="2020-11-08T09:20:01Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping Test case as it's Run Mode is set to N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping Test case as it's Run Mode is set to N
	at com.companyName.ProjectName.TestCases.TC03_CreateNewAndVerifyExistingUser.isSkip(TC03_CreateNewAndVerifyExistingUser.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isSkip -->
        <test-method status="SKIP" signature="createNewAndVerifyExistingUser(java.util.Hashtable)[pri:0, instance:com.companyName.ProjectName.TestCases.TC03_CreateNewAndVerifyExistingUser@3427b02d]" name="createNewAndVerifyExistingUser" duration-ms="0" started-at="2020-11-08T09:20:01Z" data-provider="Data_Collections" finished-at="2020-11-08T09:20:01Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping Test case as it's Run Mode is set to N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping Test case as it's Run Mode is set to N
	at com.companyName.ProjectName.TestCases.TC03_CreateNewAndVerifyExistingUser.isSkip(TC03_CreateNewAndVerifyExistingUser.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewAndVerifyExistingUser -->
      </class> <!-- com.companyName.ProjectName.TestCases.TC03_CreateNewAndVerifyExistingUser -->
    </test> <!-- Regression Test -->
  </suite> <!-- Regression Testing -->
</testng-results>
